mangas/urls.py
from django.urls import path
from . import views

app_name ='mangas'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('<int:pk>/book/', views.BookView.as_view(), name='book'),
]

mysite/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
	path('mangas/', include('mangas.urls')),
	path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

ToDo/models.py
from django.db import models

# Create your models here.

mangas/models.py
# -*- coding: utf-8 -*-

import datetime

from django.db import models
from django.utils import timezone

class Manga(models.Model):
	EN_COURS = 'KO'
	TERMINE = 'OK'
	MANGA_CHOICES = [
		(EN_COURS, 'En cours'),
		(TERMINE, 'Terminé'),
	]
	manga_name = models.CharField('Nom de la série', max_length=200)
	pub_date = models.DateField('Date de sortie de série')
	manga_end = models.CharField('Statut de la série', max_length=2, choices=MANGA_CHOICES, default=EN_COURS)
	manga_cover = models.FileField(upload_to='mangas/static/mangas', null=True, blank=True)
	manga_cover_name = models.CharField('Nom de fichier de la couverture', max_length=200, default=' ')
	def __str__(self):
		return self.manga_name
	class Meta:
		ordering = ('manga_name', )


class Book(models.Model):
	manga = models.ForeignKey(Manga, on_delete=models.CASCADE)
	book_name = models.CharField('Nom du tome', max_length=200, default=' ', blank=True)
	book_number = models.IntegerField('Numéro du tome', default=0)
	def __str__(self):
		if self.book_name == '':
			return '%s %s' % (self.manga.manga_name, self.book_number)
		else :
			return self.book_name
	class Meta:
		ordering = ( 'book_number', )


polls/models.py
import datetime

from django.db import models

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

ToDo/views.py
from django.shortcuts import render

# Create your views here.

mangas/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import *

class IndexView(generic.ListView):
    template_name = 'mangas/index.html'
    context_object_name = 'latest_manga_list'

    def get_queryset(self):
        """Return all manga list by alphabetical """
        return Manga.objects.order_by('manga_name')

class DetailView(generic.DetailView):
	model = Manga
	template_name = 'mangas/detail.html'
	#context_object_name = 'book_list'

class BookView(generic.DetailView):
	model = Book
	template_name = 'mangas/book_detail.html'


polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mangas/templates/mangas/base.html
<header id="header" class="">
	<title> La bibliothèque en ligne de TagadaBlue </title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
		integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" 
		integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"> 
	</script>
</header><!-- /header -->



 <body>
 	<h1>Voici ma bibliothèque personnelle</h1>
		{% block content %}
		{% endblock %}
 </body>

mangas/templates/mangas/book_detail.html
{% load static %}
{% extends 'mangas/base.html' %}

{% block content %}
<h1>{{book.manga.manga_name}} {{book.book_name}}</h1>


<br/>

<a href="{% url 'mangas:detail' book.manga.id %}">Retour à la liste des tomes</a> 

{% endblock %}

mangas/templates/mangas/detail.html
{% extends 'mangas/base.html' %}
{% load static %}


{% block content %}
	<h1>{{ manga.manga_name }}</h1>

	<p><strong>Date de publication du manga: </strong>{{manga.pub_date}}</p>

	<p><strong>Etat de la série:</strong>
		{% if manga.manga_end == 'OK' %} 
			Terminé 
		{% else %} 
			En cours 
		{% endif %}
	</p>

	<img src="{% static 'mangas/' %}{{manga.manga_cover_name}}" width="300px" height="400px" alt={{manga.manga_cover_name}}>

	<p><strong>Liste des différents tomes actuellement possédés:</strong> </p>

	<ul>
		{% for book in manga.book_set.all %}
		    <li>
		    	{% if book.book_name == '' %}
		    		{{ manga.manga_name }} {{ book.book_number}}
		    	{% else %}
		    		{{ book.book_name}}
		    	{% endif %}
		    	</a>
			</li>
		{% endfor %}
	</ul>

	<a href="{% url 'mangas:index' %}">Retour à la liste des mangas</a>  
{% endblock %}

mangas/templates/mangas/index.html
{% extends 'mangas/base.html' %}

{% block content %}

	<h2>Voici la liste des mangas dans la bibliothèque</h2>

	{% if latest_manga_list %}
	    <ul>
	    	{% for manga in latest_manga_list %}
	        	<li>
	        		<a href="{% url 'mangas:detail' manga.id %}">{{manga.manga_name}}</a>
	        	</li>
	    	{% endfor %}
	    </ul>
	{% else %}
	    <p>
	    	No mangas are available.
		</p>
	{% endif %}

{% endblock%}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>